#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MCM.Droid.Classic.Resource", IsApplication=true)]

namespace MCM.Droid.Classic
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_add_person = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_cancel = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_discard = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_save = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sample_0 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sample_1 = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060028
			public const int AboutMCMButton = 2131099688;
			
			// aapt resource value: 0x7f060017
			public const int AddPhotoButton = 2131099671;
			
			// aapt resource value: 0x7f060011
			public const int Age = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int AgeLabel = 2131099664;
			
			// aapt resource value: 0x7f060023
			public const int BypassLoginButton = 2131099683;
			
			// aapt resource value: 0x7f060013
			public const int CheckListLabel = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int CheckListLayout = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int ChildBasicsButton = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int ChildPhotoImageView = 2131099670;
			
			// aapt resource value: 0x7f060029
			public const int ChildrenListView = 2131099689;
			
			// aapt resource value: 0x7f06000c
			public const int DateDisplayTextView = 2131099660;
			
			// aapt resource value: 0x7f06001c
			public const int DentalInfoButton = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int DistinguishingFeaturesButton = 2131099678;
			
			// aapt resource value: 0x7f06001b
			public const int DoctorInfoButton = 2131099675;
			
			// aapt resource value: 0x7f06000f
			public const int FirstName = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int FirstNameText = 2131099653;
			
			// aapt resource value: 0x7f060021
			public const int GmailLoginButton = 2131099681;
			
			// aapt resource value: 0x7f060025
			public const int HomeDNAButton = 2131099685;
			
			// aapt resource value: 0x7f060020
			public const int HotmailLoginButton = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int IDChecklistButton = 2131099679;
			
			// aapt resource value: 0x7f060015
			public const int Image = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int LastNameText = 2131099657;
			
			// aapt resource value: 0x7f060019
			public const int MeasurementsButton = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int MedicalAlertInfoButton = 2131099677;
			
			// aapt resource value: 0x7f060007
			public const int MiddleNameText = 2131099655;
			
			// aapt resource value: 0x7f060027
			public const int MissingChildButton = 2131099687;
			
			// aapt resource value: 0x7f060002
			public const int MyButton = 2131099650;
			
			// aapt resource value: 0x7f060024
			public const int MyChildrenButton = 2131099684;
			
			// aapt resource value: 0x7f060014
			public const int PercentComplete = 2131099668;
			
			// aapt resource value: 0x7f06001a
			public const int PhysicalDetailsButton = 2131099674;
			
			// aapt resource value: 0x7f06000d
			public const int PickDateButton = 2131099661;
			
			// aapt resource value: 0x7f060026
			public const int SafetyForChildrenButton = 2131099686;
			
			// aapt resource value: 0x7f06000e
			public const int Text = 2131099662;
			
			// aapt resource value: 0x7f060022
			public const int TwitterLoginButton = 2131099682;
			
			// aapt resource value: 0x7f060003
			public const int imageView1 = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout1 = 2131099659;
			
			// aapt resource value: 0x7f06002d
			public const int menu_add_child = 2131099693;
			
			// aapt resource value: 0x7f06002b
			public const int menu_cancel_info = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int menu_delete_info = 2131099692;
			
			// aapt resource value: 0x7f06002a
			public const int menu_save_info = 2131099690;
			
			// aapt resource value: 0x7f060001
			public const int myButton = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int textView3 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int textView4 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int textView5 = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int textView6 = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutMCM = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddPhoto = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChildBasics = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChildListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ChildProfile = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DentalInfo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DistinguishingFeatures = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DoctorInfo = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int HomeDNA = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int IDChecklist = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MCM = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Measurements = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int MedicalAlertInfo = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int MissingChild = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int MyChildren = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int PhysicalDetails = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int SafetyForChildren = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu_childbasics = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menu_mychildren = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int menu_save_cancel = 2131034114;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int aboutmcm_layout_label = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int addphoto_layout_label = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040026
			public const int childbasics_dateofbirth_textview_text = 2130968614;
			
			// aapt resource value: 0x7f040023
			public const int childbasics_firstname_textview_text = 2130968611;
			
			// aapt resource value: 0x7f040025
			public const int childbasics_lastname_textview_text = 2130968613;
			
			// aapt resource value: 0x7f040006
			public const int childbasics_layout_label = 2130968582;
			
			// aapt resource value: 0x7f040024
			public const int childbasics_middlename_textview_text = 2130968612;
			
			// aapt resource value: 0x7f040027
			public const int childbasics_pickdate_button_text = 2130968615;
			
			// aapt resource value: 0x7f04001a
			public const int childprofile_addphoto_button_text = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int childprofile_childbasics_button_text = 2130968603;
			
			// aapt resource value: 0x7f04001f
			public const int childprofile_dentalinfo_button_text = 2130968607;
			
			// aapt resource value: 0x7f040021
			public const int childprofile_distinguishingfeatures_button_text = 2130968609;
			
			// aapt resource value: 0x7f04001e
			public const int childprofile_doctorinfo_button_text = 2130968606;
			
			// aapt resource value: 0x7f040022
			public const int childprofile_idchecklist_button_text = 2130968610;
			
			// aapt resource value: 0x7f040007
			public const int childprofile_layout_label = 2130968583;
			
			// aapt resource value: 0x7f04001c
			public const int childprofile_measurements_button_text = 2130968604;
			
			// aapt resource value: 0x7f040020
			public const int childprofile_medicalalertinfo_button_text = 2130968608;
			
			// aapt resource value: 0x7f04001d
			public const int childprofile_physicaldetails_button_text = 2130968605;
			
			// aapt resource value: 0x7f040008
			public const int dentalinfo_layout_label = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int distinguishingfeatures_layout_label = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int doctorinfo_layout_label = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int gmail_login_button_text = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int homedna_layout_label = 2130968587;
			
			// aapt resource value: 0x7f040001
			public const int hotmail_login_button_text = 2130968577;
			
			// aapt resource value: 0x7f04000c
			public const int idchecklist_layout_label = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int main_layout_label = 2130968589;
			
			// aapt resource value: 0x7f040019
			public const int mcm_aboutmcm_button_text = 2130968601;
			
			// aapt resource value: 0x7f040016
			public const int mcm_homedna_button_text = 2130968598;
			
			// aapt resource value: 0x7f04000e
			public const int mcm_layout_label = 2130968590;
			
			// aapt resource value: 0x7f040018
			public const int mcm_missingchild_button_text = 2130968600;
			
			// aapt resource value: 0x7f040015
			public const int mcm_mychildren_button_text = 2130968597;
			
			// aapt resource value: 0x7f040017
			public const int mcm_safetyforchildren_button_text = 2130968599;
			
			// aapt resource value: 0x7f04000f
			public const int measurements_layout_label = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int medicalalertinfo_layout_label = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int missingchild_layout_label = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int mychildren_layout_label = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int physicaldetails_layout_label = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int safetyforchildren_layout_label = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int twitter_login_button_text = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
