#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MCM.Resource", IsApplication=true)]

namespace MCM
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int sample_0 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sample_1 = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050013
			public const int AboutMCMButton = 2131034131;
			
			// aapt resource value: 0x7f050002
			public const int AddPhotoButton = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int BypassLoginButton = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int ChildBasicsButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int ChildPhotoImageView = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int DentalInfoButton = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int DistinguishingFeaturesButton = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int DoctorInfoButton = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int GmailLoginButton = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int HomeDNAButton = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int HotmailLoginButton = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int IDChecklistButton = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int MeasurementsButton = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int MedicalAlertInfoButton = 2131034120;
			
			// aapt resource value: 0x7f050012
			public const int MissingChildButton = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int MyChildrenButton = 2131034127;
			
			// aapt resource value: 0x7f050005
			public const int PhysicalDetailsButton = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int SafetyForChildrenButton = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int TwitterLoginButton = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int imageView1 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout1 = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050016
			public const int textView2 = 2131034134;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutMCM = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddPhoto = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChildBasics = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChildProfile = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DentalInfo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DistinguishingFeatures = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DoctorInfo = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HomeDNA = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int IDChecklist = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MCM = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Measurements = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MedicalAlertInfo = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int MissingChild = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int MyChildren = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PhysicalDetails = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SafetyForChildren = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int aboutmcm_label = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int childprofile_addphoto_button_text = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int childprofile_childbasics_button_text = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int childprofile_dentalinfo_button_text = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int childprofile_distinguishingfeatures_button_text = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int childprofile_doctorinfo_button_text = 2130968590;
			
			// aapt resource value: 0x7f040012
			public const int childprofile_idchecklist_button_text = 2130968594;
			
			// aapt resource value: 0x7f04000c
			public const int childprofile_measurements_button_text = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int childprofile_medicalalertinfo_button_text = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int childprofile_physicaldetails_button_text = 2130968589;
			
			// aapt resource value: 0x7f040002
			public const int gmail_login_button_text = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hotmail_login_button_text = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int mcm_aboutmcm_button_text = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int mcm_homedna_button_text = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int mcm_missingchild_button_text = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int mcm_mychildren_button_text = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int mcm_safetyforchildren_button_text = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int twitter_login_button_text = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
